//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HatFClient.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HatFClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;Code&quot;: 0,
        ///    &quot;Name&quot;: &quot;未設定&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 15,
        ///    &quot;Name&quot;: &quot;15日締め&quot;
        ///  }
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_CloseDate {
            get {
                return ResourceManager.GetString("HatF_CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;Code&quot;: null,
        ///    &quot;Name&quot;: &quot;未設定&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 1,
        ///    &quot;Name&quot;: &quot;都度請求&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 2,
        ///    &quot;Name&quot;: &quot;締請求&quot;
        ///  }
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_CustArFlag {
            get {
                return ResourceManager.GetString("HatF_CustArFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///	{
        ///		&quot;id&quot;:&quot;BT001&quot;,
        ///		&quot;message&quot;:&quot;必須入力項目です。&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;:&quot;BT002&quot;,
        ///		&quot;message&quot;:&quot;伝票分割をしてください。&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;:&quot;BT003&quot;,
        ///		&quot;message&quot;:&quot;すべて数字を入力してください。&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;:&quot;BT004&quot;,
        ///		&quot;message&quot;:&quot;同じ注文番号の伝票番号は重複できません。&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;:&quot;BT005&quot;,
        ///		&quot;message&quot;:&quot;在庫または取次の時、過去日付を入力できません。&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;:&quot;BT006&quot;,
        ///		&quot;message&quot;:&quot;発注方法を3：手動に変更して下さい。&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;:&quot;BT007&quot;,
        ///		&quot;message&quot;:&quot;90日以上未来を入力できません。&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;:&quot;BT008&quot;,
        ///		&quot;message&quot;:&quot;取次の照合時、1年以上未来日付を入力できません。&quot;
        ///	},
        ///	{
        ///		&quot;id&quot;:&quot;BT009&quot;,
        ///		&quot;message&quot;:&quot;取次 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_ErrorMessage_Button {
            get {
                return ResourceManager.GetString("HatF_ErrorMessage_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;id&quot;: &quot;FO001&quot;,
        ///    &quot;name&quot;: &quot;日付チェック&quot;,
        ///    &quot;explanation&quot;: &quot;入力がある かつ 日付として正しい入力ではない&quot;,
        ///    &quot;message&quot;: &quot;正しい日付を入力してください。&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;FO002&quot;,
        ///    &quot;name&quot;: &quot;半角英大文字数字チェック&quot;,
        ///    &quot;explanation&quot;: &quot;入力があり かつ 半角の英大文字または数字以外が含まれる&quot;,
        ///    &quot;message&quot;: &quot;半角の英大文字または数字を入力してください。&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;FO003&quot;,
        ///    &quot;name&quot;: &quot;半角ハイフン数字チェック&quot;,
        ///    &quot;explanation&quot;: &quot;入力があり かつ 半角の「-」（ハイフン）または数字以外が含まれる&quot;,
        ///    &quot;message&quot;: &quot;半角の「-」（ハイフン）または数字を入力してください。&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;FO004&quot;,
        ///    &quot;name&quot;: &quot;半角チェック&quot;,
        ///    &quot;expla [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_ErrorMessage_FocusOut {
            get {
                return ResourceManager.GetString("HatF_ErrorMessage_FocusOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;key&quot;: &quot;1&quot;,
        ///    &quot;name&quot;: &quot;発注前&quot;,
        ///    &quot;style&quot;: &quot;AddStyle1&quot;,
        ///    &quot;color&quot;: &quot;LightYellow&quot;
        ///  },
        ///  {
        ///    &quot;key&quot;: &quot;2&quot;,
        ///    &quot;name&quot;: &quot;手配中・回答待&quot;,
        ///    &quot;style&quot;: &quot;AddStyle2&quot;,
        ///    &quot;color&quot;: &quot;LightGreen&quot;
        ///  },
        ///  {
        ///    &quot;key&quot;: &quot;3&quot;,
        ///    &quot;name&quot;: &quot;ACOS済&quot;,
        ///    &quot;style&quot;: &quot;AddStyle3&quot;,
        ///    &quot;color&quot;: &quot;White&quot;
        ///  },
        ///  {
        ///    &quot;key&quot;: &quot;4&quot;,
        ///    &quot;name&quot;: &quot;削除&quot;,
        ///    &quot;style&quot;: &quot;AddStyle4&quot;,
        ///    &quot;color&quot;: &quot;White&quot;
        ///  },
        ///  {
        ///    &quot;key&quot;: &quot;5&quot;,
        ///    &quot;name&quot;: &quot;逸注&quot;,
        ///    &quot;style&quot;: &quot;AddStyle5&quot;,
        ///    &quot;color&quot;: &quot;White&quot;
        ///  },
        ///  {
        ///     [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_HattyuJyoutai {
            get {
                return ResourceManager.GetString("HatF_HattyuJyoutai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///	{
        ///		&quot;key&quot;: &quot;0&quot;,
        ///		&quot;name&quot;: &quot;未確認&quot;,
        ///		&quot;color&quot;: &quot;Yellow&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;: &quot;1&quot;,
        ///		&quot;name&quot;: &quot;確認済&quot;,
        ///		&quot;color&quot;: &quot;LightBlue&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;: &quot;2&quot;,
        ///		&quot;name&quot;: &quot;編集中&quot;,
        ///		&quot;color&quot;: &quot;LightGreen&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;: &quot;3&quot;,
        ///		&quot;name&quot;: &quot;違算&quot;,
        ///		&quot;color&quot;: &quot;Pink&quot;
        ///	}
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_InvoiceConfirmation {
            get {
                return ResourceManager.GetString("HatF_InvoiceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;Code&quot;: 0,
        ///    &quot;Name&quot;: &quot;取引可&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 1,
        ///    &quot;Name&quot;: &quot;取引禁止&quot;
        ///  }
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_NoSalesFlg {
            get {
                return ResourceManager.GetString("HatF_NoSalesFlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///	{
        ///		&quot;key&quot;:&quot;1&quot;,
        ///		&quot;name&quot;:&quot;通常受注&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:&quot;2&quot;,
        ///		&quot;name&quot;:&quot;見積受注&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:&quot;3&quot;,
        ///		&quot;name&quot;:&quot;OPS&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:&quot;4&quot;,
        ///		&quot;name&quot;:&quot;HOPE&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:&quot;5&quot;,
        ///		&quot;name&quot;:&quot;請書取込&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:&quot;6&quot;,
        ///		&quot;name&quot;:&quot;エプコ取込&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:&quot;7&quot;,
        ///		&quot;name&quot;:&quot;新OPS&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:&quot;8&quot;,
        ///		&quot;name&quot;:&quot;OCR&quot;
        ///	}
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_OrderFlag {
            get {
                return ResourceManager.GetString("HatF_OrderFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///	{
        ///		&quot;Code&quot;: 1,
        ///		&quot;Name&quot;: &quot;1日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 2,
        ///		&quot;Name&quot;: &quot;2日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 3,
        ///		&quot;Name&quot;: &quot;3日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 4,
        ///		&quot;Name&quot;: &quot;4日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 5,
        ///		&quot;Name&quot;: &quot;5日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 6,
        ///		&quot;Name&quot;: &quot;6日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 7,
        ///		&quot;Name&quot;: &quot;7日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 8,
        ///		&quot;Name&quot;: &quot;8日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 9,
        ///		&quot;Name&quot;: &quot;9日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 10,
        ///		&quot;Name&quot;: &quot;10日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 11,
        ///		&quot;Name&quot;: &quot;11日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: 12,
        ///		&quot;Name&quot;: &quot;12日払い&quot;
        ///	},
        ///	{
        ///		&quot;Code [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_PayDates {
            get {
                return ResourceManager.GetString("HatF_PayDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///	{
        ///		&quot;key&quot;:null,
        ///		&quot;name&quot;:&quot;未設定&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:1,
        ///		&quot;name&quot;:&quot;振込&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:2,
        ///		&quot;name&quot;:&quot;手形&quot;
        ///	}
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_PaymentClassification {
            get {
                return ResourceManager.GetString("HatF_PaymentClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///	{
        ///		&quot;key&quot;:null,
        ///		&quot;name&quot;:&quot;未設定&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:10,
        ///		&quot;name&quot;:&quot;10日払い&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:99,
        ///		&quot;name&quot;:&quot;末日&quot;
        ///	}
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_PaymentDay {
            get {
                return ResourceManager.GetString("HatF_PaymentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///	{
        ///		&quot;key&quot;:null,
        ///		&quot;name&quot;:&quot;未設定&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:0,
        ///		&quot;name&quot;:&quot;当月&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:1,
        ///		&quot;name&quot;:&quot;翌月&quot;
        ///	},
        ///	{
        ///		&quot;key&quot;:2,
        ///		&quot;name&quot;:&quot;翌々月&quot;
        ///	}
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_PaymentMonth {
            get {
                return ResourceManager.GetString("HatF_PaymentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///    {
        ///        &quot;Code&quot;: 1,
        ///        &quot;Name&quot;: &quot;振込&quot;
        ///    },
        ///    {
        ///        &quot;Code&quot;: 2,
        ///        &quot;Name&quot;: &quot;手形&quot;
        ///    },
        ///    {
        ///        &quot;Code&quot;: 3,
        ///        &quot;Name&quot;: &quot;でんさい&quot;
        ///    }
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_PayMethodType {
            get {
                return ResourceManager.GetString("HatF_PayMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;Code&quot;: 0,
        ///    &quot;Name&quot;: &quot;当月&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 1,
        ///    &quot;Name&quot;: &quot;翌月&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 2,
        ///    &quot;Name&quot;: &quot;翌々月&quot;
        ///  }
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_PayMonths {
            get {
                return ResourceManager.GetString("HatF_PayMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;Code&quot;: 1,
        ///    &quot;Name&quot;: &quot;協賛金&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 2,
        ///    &quot;Name&quot;: &quot;保険&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 3,
        ///    &quot;Name&quot;: &quot;経費&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 4,
        ///    &quot;Name&quot;: &quot;商品購入&quot;
        ///  }
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_SalesAdjustmentCategory {
            get {
                return ResourceManager.GetString("HatF_SalesAdjustmentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;Code&quot;: 0,
        ///    &quot;Name&quot;: &quot;未設定&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 1,
        ///    &quot;Name&quot;: &quot;橋本本体&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: 2,
        ///    &quot;Name&quot;: &quot;橋本本体以外&quot;
        ///  }
        ///]
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HatF_SupplierType {
            get {
                return ResourceManager.GetString("HatF_SupplierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap image_2024_5_28 {
            get {
                object obj = ResourceManager.GetObject("image_2024_5_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   [
        ///    {
        ///        &quot;name&quot;: &quot;DIV_SOKO&quot;,
        ///        &quot;logical_name&quot;: &quot;DIV_倉庫&quot;,
        ///        &quot;columns&quot;: [
        ///            {
        ///                &quot;name&quot;: &quot;SOKO_CD&quot;,
        ///                &quot;logical_name&quot;: &quot;倉庫コード&quot;,
        ///                &quot;primary_key&quot;: true,
        ///                &quot;unique&quot;: false,
        ///                &quot;max_length&quot;: 2,
        ///                &quot;number_only&quot;: true
        ///            },
        ///            {
        ///                &quot;name&quot;: &quot;SOKO_NAME&quot;,
        ///                &quot;logical_name&quot;: &quot;倉庫名&quot;,
        ///                &quot;primary_key&quot;: false,
        ///                &quot;unique&quot;: true,        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string master_meta_data {
            get {
                return ResourceManager.GetString("master_meta_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap menu_hatena_illust {
            get {
                object obj = ResourceManager.GetObject("menu_hatena_illust", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;Code&quot;: null,
        ///    &quot;Area&quot;: null,
        ///    &quot;Name&quot;: null
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;01&quot;,
        ///    &quot;Area&quot;: &quot;北海道&quot;,
        ///    &quot;Name&quot;: &quot;北海道&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;02&quot;,
        ///    &quot;Area&quot;: &quot;東北&quot;,
        ///    &quot;Name&quot;: &quot;青森県&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;03&quot;,
        ///    &quot;Area&quot;: &quot;東北&quot;,
        ///    &quot;Name&quot;: &quot;岩手県&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;04&quot;,
        ///    &quot;Area&quot;: &quot;東北&quot;,
        ///    &quot;Name&quot;: &quot;宮城県&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;05&quot;,
        ///    &quot;Area&quot;: &quot;東北&quot;,
        ///    &quot;Name&quot;: &quot;秋田県&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;06&quot;,
        ///    &quot;Area&quot;: &quot;東北&quot;,
        ///    &quot;Name&quot;: &quot;山形県&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;07&quot;,
        ///    &quot;Area [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string prefectures {
            get {
                return ResourceManager.GetString("prefectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon SUBARU {
            get {
                object obj = ResourceManager.GetObject("SUBARU", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap transparency_notes_icon {
            get {
                object obj = ResourceManager.GetObject("transparency_notes_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap transparency_notes_icon_red {
            get {
                object obj = ResourceManager.GetObject("transparency_notes_icon_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap transparency_search_icon {
            get {
                object obj = ResourceManager.GetObject("transparency_search_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
